variables:
  HELM_VERSION: "3.3.3"
  HELM_CHECKSUM: "246d58b6b353e63ae8627415a7340089015e3eb542ff7b5ce124b0b1409369cc"
  DOCKER_BUILD_ARGS: '--build-arg\ HELM_VERSION_ARG=$HELM_VERSION\ --build-arg\ HELM_CHECKSUM_ARG=$HELM_CHECKSUM'

include:
  - project: 'shared/gitlab/gitlab-templates'
    ref: 'tags/1.11'
    file: 'docker_build.yml'
