image:
  name: gcr.io/kaniko-project/executor:debug
  entrypoint: [""]

variables:
  REGISTRY: docker.vpro.nl
  HELM_VERSION: "3.3.1"
  HELM_CHECKSUM: "87d302b754b6f702f4308c2aff190280ff23cc21c35660ef93d78c39158d796f"

stages:
  - develop
  - release

.build: &build
  script:
    - setup_kaniko
    - kaniko_execute

develop:
  <<: *build
  stage: develop
  before_script:
    - export IMAGE_TAG=$REGISTRY/openshift-helm:dev
  only:
    - master
    - /^feature\/.*/

release:
  <<: *build
  stage: release
  before_script:
    - export IMAGE_TAG=$REGISTRY/openshift-helm:$CI_COMMIT_TAG
  only:
    - tags

.build_setup: &build_setup |
  [[ "$TRACE" ]] && set -x

  function setup_kaniko() {
    mkdir -p /kaniko/.docker
    cp $DOCKER_AUTH_CONFIG /kaniko/.docker/config.json
  }

  function kaniko_execute() {
    echo "Building and pushing image: \"$IMAGE_TAG\""

    /kaniko/executor --context $CI_PROJECT_DIR \
      && --dockerfile $CI_PROJECT_DIR/Dockerfile \
      && --build-arg HELM_VERSION_ARG=$HELM_VERSION \
      && --build-arg HELM_CHECKSUM_ARG=$HELM_CHECKSUM \
      && --cache=false \
      && --destination $IMAGE_TAG
  }

before_script:
  - *build_setup

