image:
  name: gcr.io/kaniko-project/executor:debug
  entrypoint: [""]

variables:
  REGISTRY: docker.vpro.nl
  HELM_VERSION: "3.3.3"
  HELM_CHECKSUM: "246d58b6b353e63ae8627415a7340089015e3eb542ff7b5ce124b0b1409369cc"

stages:
  - develop
  - release

.build: &build
  script:
    - setup_kaniko
    - kaniko_execute

develop:
  <<: *build
  stage: develop
  variables:
    IMAGE_VERSION: dev
  only:
    - master
    - /^feature\/.*/

release:
  <<: *build
  stage: release
  variables:
    IMAGE_VERSION: $CI_COMMIT_TAG # TODO Check if this works
  only:
    - tags

# ---------------------------------------------------------------------------

.build_setup: &build_setup |
  [[ "$TRACE" ]] && set -x

  export IMAGE_TAG=$REGISTRY/openshift-helm:$IMAGE_VERSION

  function setup_kaniko() {
    mkdir -p /kaniko/.docker
    cp $DOCKER_AUTH_CONFIG /kaniko/.docker/config.json
  }

  function kaniko_execute() {
    echo "Building and pushing image: \"$IMAGE_TAG\""

    /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --build-arg HELM_VERSION_ARG=$HELM_VERSION --build-arg HELM_CHECKSUM_ARG=$HELM_CHECKSUM --cache=false --destination $IMAGE_TAG
  }

before_script:
  - *build_setup

